### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by de-quei** [cuzurmyhabit/2024_java_project#1]
Q1. IDE 어떤거 사용하시나요?

제안1. File Structure에 대해 고민해보시는게 좋을 것 같아요. 프로젝트 폴더 루트 경로에 파일들이 촤라락 있는 것 보다 "java 폴더구조" 검색해보셔서 구조적으로 진행하시는게 좋을 것 같아요!

제안2. 코드에 주석 더 달아주시면 좋을 것 같아요!

제안3. 로그인 기능에서 ArrayList는 실행할때마다 데이터가 초기화돼요! add말고 JDBC Driver 추가해서 MySQL 사용해보세요! GUI를 사용하지 않는다면 수행평가용으로 DB를 사용하는게 점수가 높게 나올거에요

**Comment by cuzurmyhabit** [comment]
A1. 현재 IntelliJ를 사용하고 있습니다!

조언 감사합니다. 폴더 구조에 대해 더 공부해 보겠습니다! 또한 코드 주석도 열심히 다는 습관... 길러 보겠습니다! ㅠㅠ

로그인 기능에서 뿐만 아니라 신청, 제출 등을 최대한 MySQL을 사용해 DB 연동을 해 보려고는 하는 중인데, 생각처럼 되지 않아서 일단 add로 넣어뒀습니다. ㅠㅠ
